# Generated by the varis-cli release workflow (scripts/homebrew-formula.sh
# in usevaris/varis-cli). Don't edit it here: each release replaces it.
class Varis < Formula
  desc "Publish services that AI agents discover and pay to use"
  homepage "https://github.com/usevaris/varis-cli"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/usevaris/varis-cli/releases/download/v1.0.1/varis-darwin-arm64.tar.gz"
      sha256 "55bd0ac90d4450305a5aa54f9895de9b944651e841392582c395e5065e04db4f"
    end
    on_intel do
      url "https://github.com/usevaris/varis-cli/releases/download/v1.0.1/varis-darwin-x64.tar.gz"
      sha256 "2cfe5fc9df3c04baf0c5441001b88fa94cdcabf259ead8908390a55c65a5060b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/usevaris/varis-cli/releases/download/v1.0.1/varis-linux-arm64.tar.gz"
      sha256 "597e4ae3096354e46092dfd7824a5b9784eb1b065c485ea9a09077656f700060"
    end
    on_intel do
      url "https://github.com/usevaris/varis-cli/releases/download/v1.0.1/varis-linux-x64.tar.gz"
      sha256 "e23661c75de7e4e2e425a6817c5f5636dec5ea5076b12a89c82a6e55d52b56fa"
    end
  end

  def install
    bin.install "varis"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/varis --version").strip
  end
end
