# Generated by the varis-cli release workflow (scripts/homebrew-formula.sh
# in usevaris/varis-cli). Don't edit it here: each release replaces it.
class Varis < Formula
  desc "Publish services that AI agents discover and pay to use"
  homepage "https://github.com/usevaris/varis-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/usevaris/varis-cli/releases/download/v1.0.0/varis-darwin-arm64.tar.gz"
      sha256 "6e99e25b63807ae17148367fc228068a2b8bdb379e1288ef8424d547ac47ec35"
    end
    on_intel do
      url "https://github.com/usevaris/varis-cli/releases/download/v1.0.0/varis-darwin-x64.tar.gz"
      sha256 "584d965201d3129a16b361141edf779a02c00dbd543c6553d4013819dd4d3c3f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/usevaris/varis-cli/releases/download/v1.0.0/varis-linux-arm64.tar.gz"
      sha256 "35dd62d1f182926bb1dc25769c5aebe02ee8c27b89eecd2bce1571cbb60304de"
    end
    on_intel do
      url "https://github.com/usevaris/varis-cli/releases/download/v1.0.0/varis-linux-x64.tar.gz"
      sha256 "2e2b4b73eff0f08e7d8032efb0c3e6f660ffed62e546d61316b020da43bfd579"
    end
  end

  def install
    bin.install "varis"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/varis --version").strip
  end
end
